### ISSUE TITLE
モバイルで地図を表示時にコピーライトが3つ表示される

### ISSUE THREAD

**Issue by naogify** [geolonia/embed#235]
下のURLをスマホで表示すると画像のように、コピーライトボタンが3つ表示されてしまう。

https://codepen.io/geolonia/pen/rNwMxRx

![Image from iOS](https://user-images.githubusercontent.com/8760841/132120988-9a3a0d74-ba74-4d22-8760-5e1cba32f05a.png)

**Comment by kamataryo** [comment]
- iOS Safari で、 CodePen 上でのみ再現するよう

**Comment by kamataryo** [comment]
@naogify 
あ、わかりました。これで崩れているんだと思います。

```css
input, button
{
  font-size: 32px;
}
```

**Comment by kamataryo** [comment]
CodePen の方で対応済み。 32px = 1em が コントロール内部のボタンの padding を上書きして崩れていた。

```css
#addr, #btn
{
  font-size: 32px;
}
```
